.\" Copyright 2022 Dávid Csaba Mezőfi
.\" 
.\" Copying and distribution of this file, with or without modification, are
.\" permitted in any medium without royalty provided the copyright notice and
.\" this notice are preserved.  This file is offered as-is, without any
.\" warranty.
.
.TH "PUNCH.SH" 1 "2022-02-05"
.
.SH NAME
punch.sh \- install fonts for groff
.
.SH SYNOPSIS
.SY punch.sh
.OP \-h
.OP \-g groffpath
.OP \-v groffversion
.OP \-f fontpath
.I fontfile
.I fontname
.YS
.
.SH DESCRIPTION
.PP
The shells script
.B punch.sh
automates the process of installing fonts for groff.
.PP
The first argument
.I fontfile
shall be a TrueType (TTF), OpenType (OTF) or Type 1 (PFA) font file.  The
second argument
.I fontname
shall be the groff font name, e.g. \c
.IR MyFontR .
The recommended naming convention is to use the letters
.BR R ,
.BR B ,
.B I
and
.B BI 
as postfixes in
.I fontname
for roman, italic, bold and bold italic font faces, respectively.  In the
example above
.I MyFontR
would stand for the roman font of the
.I MyFont
font family.
.PP
If an error occurs, then the script tries to report to
.B stderr
what happened.
.PP
Most likely the script needs to be run as root, but it depends on your rights
to the local font directory where the font will be installed.
.
.SH OPTIONS
.TP
.B \-h
Print the usage of the script.
.TP
\fB\-g\fR \fIgroffpath\fR
Set the path to groff to
.I groffpath
(set to
.I /usr/share/groff
by default).
.IP
See \(lqDirectory\ for\ data\ files.\(rq under the
.B INSTALLATION\ DIRECTORIES
section in the man page of groff to find out your
.IR groffpath .
.TP
\fB\-v\fR \fIgroffversion\fR
Set the version of groff installed to
.I groffversion
(set to
.I 1.22.4
by default).
.IP
See \(lqDirectory\ for\ data\ files.\(rq under the
.B INSTALLATION\ DIRECTORIES
section in the man page of groff to find out your
.IR groffversion .
.TP
\fB\-f\fR \fIfontpath\fR
Set
.I fontpath
as the local font directory of groff (set to
.I /etc/groff/site-font
by default).  Your generated font files will be installed under this directory.
.IP
See \(lqLocal\ font\ directory.\(rq under the
.B INSTALLATION\ DIRECTORIES
section in the man page of groff to find out your
.IR fontpath .
.
.SH EXIT STATUS
.TP
0
The execution of the script was successful
.TP
1
Incorrect options or arguments were provided
.TP
2
fontforge is not in
.B $PATH
.TP
3
Missing files
.TP
4
The temporary directory
.I /tmp/fontbuild
was already existing at the start of the script
.
.SH NOTES
The script punch.sh was inspired by the 
.UR https://www.schaffter.ca/mom/momdoc/appendices.html#fonts
install-font.sh script
.UE
by Peter Schaffter.
.
.SH SEE ALSO
.BR afmtodit (1),
.BR fontforge (1),
.BR groff (1),
.BR gropdf (1),
.BR grops (1),
.BR groff_mom (7)
